apiVersion: v1
kind: Service
metadata:
  name: dev-deploy
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 80
  selector:
    app: dev-deploy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-deploy
  template:
    metadata:
      labels:
        app: dev-deploy
    spec:
      containers:
      - name: hello-kubernetes
        image: sreeharshav/testcontainer:v1
        ports:
        - containerPort: 80
